/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Mod {
  'id' : bigint,
  'title' : string,
  'game' : string,
  'description' : string,
  'fileName' : string,
  'fileSize' : bigint,
  'uploadTimestamp' : Time,
  'author' : string,
  'category' : string,
  'downloadCount' : bigint,
}
export interface ModUpload {
  'title' : string,
  'game' : string,
  'description' : string,
  'fileName' : string,
  'fileSize' : bigint,
  'author' : string,
  'category' : string,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteMod' : ActorMethod<[bigint], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getModById' : ActorMethod<[bigint], Mod>,
  'getModsByAuthor' : ActorMethod<[string], Array<Mod>>,
  'getModsByCategory' : ActorMethod<[string], Array<Mod>>,
  'getPopularMods' : ActorMethod<[bigint], Array<Mod>>,
  'incrementDownloadCount' : ActorMethod<[bigint], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMods' : ActorMethod<[bigint, bigint], Array<Mod>>,
  'uploadMod' : ActorMethod<[ModUpload], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];