/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Mod = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'game' : IDL.Text,
  'description' : IDL.Text,
  'fileName' : IDL.Text,
  'fileSize' : IDL.Nat,
  'uploadTimestamp' : Time,
  'author' : IDL.Text,
  'category' : IDL.Text,
  'downloadCount' : IDL.Nat,
});
export const ModUpload = IDL.Record({
  'title' : IDL.Text,
  'game' : IDL.Text,
  'description' : IDL.Text,
  'fileName' : IDL.Text,
  'fileSize' : IDL.Nat,
  'author' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMod' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getModById' : IDL.Func([IDL.Nat], [Mod], ['query']),
  'getModsByAuthor' : IDL.Func([IDL.Text], [IDL.Vec(Mod)], ['query']),
  'getModsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Mod)], ['query']),
  'getPopularMods' : IDL.Func([IDL.Nat], [IDL.Vec(Mod)], ['query']),
  'incrementDownloadCount' : IDL.Func([IDL.Nat], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMods' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Mod)], ['query']),
  'uploadMod' : IDL.Func([ModUpload], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Mod = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'game' : IDL.Text,
    'description' : IDL.Text,
    'fileName' : IDL.Text,
    'fileSize' : IDL.Nat,
    'uploadTimestamp' : Time,
    'author' : IDL.Text,
    'category' : IDL.Text,
    'downloadCount' : IDL.Nat,
  });
  const ModUpload = IDL.Record({
    'title' : IDL.Text,
    'game' : IDL.Text,
    'description' : IDL.Text,
    'fileName' : IDL.Text,
    'fileSize' : IDL.Nat,
    'author' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMod' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getModById' : IDL.Func([IDL.Nat], [Mod], ['query']),
    'getModsByAuthor' : IDL.Func([IDL.Text], [IDL.Vec(Mod)], ['query']),
    'getModsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Mod)], ['query']),
    'getPopularMods' : IDL.Func([IDL.Nat], [IDL.Vec(Mod)], ['query']),
    'incrementDownloadCount' : IDL.Func([IDL.Nat], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMods' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Mod)], ['query']),
    'uploadMod' : IDL.Func([ModUpload], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };